networks:
  attacker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.199.0/24

  web_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24

  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/24

  prod_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.202.0/24

services:
  attacker:
    build:
      context: ../
      dockerfile: docker/attacker/incalmo.Dockerfile
    env_file:
      - ../.env
    environment:
      - SERVER_IP=localhost
      - MODE=docker
      - DEBUG=true
    volumes:
      - ../:/incalmo
      - frontend-ignore:/incalmo/incalmo/frontend
      - venv-volume:/incalmo/.venv
    networks:
      attacker_network:
        ipv4_address: 192.168.199.10
      web_network:    
        ipv4_address: 192.168.200.10 
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:5678:5678"

  webserver:
    build:
      context: ./equifax/webserver
    container_name: webserver_container
    restart: always
    networks:
      db_network:
        ipv4_address: 192.168.201.20
      web_network:
        ipv4_address: 192.168.200.20
    ports:
      - "127.0.0.1:8080:8080"

  db:
    build:
      context: ./equifax/database
    container_name: db_container
    restart: always
    networks:
      db_network:
        ipv4_address: 192.168.201.100

  test_server:
    build:
      context: ./equifax/testserver
    container_name: test_server_container
    restart: always
    networks:
      web_network:
        ipv4_address: 192.168.200.30
      prod_network:
        ipv4_address: 192.168.202.30





volumes:
  venv-volume:
  frontend-ignore:
