# defines the simulated internal network topology 
networks:

  # 3 containers/services 
  # things on the same subnet can talk to each other 
  attacker_network:
    driver: bridge # each network is a virtual LAN/subnet inside docker unless a container is attached to both
    ipam: # IP address management
      config:
        - subnet: 192.168.199.0/24 # defines the LAN itself

  web_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24

  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/24

services:
  attacker:
    build:
      context: ../
      dockerfile: docker/attacker/incalmo.Dockerfile
    env_file:
      - ../.env
    environment:
      - SERVER_IP=localhost
      - MODE=docker
      - DEBUG=true
    volumes:
      - ../:/incalmo
      - frontend-ignore:/incalmo/incalmo/frontend
      - venv-volume:/incalmo/.venv

    # attacker container is connected to two networks -- can directly communicate with them
    networks:
      attacker_network:
        ipv4_address: 192.168.199.10 # attaches container attacker to the attacker_network
      web_network:    
        ipv4_address: 192.168.200.10 
    ports: # connects ports on local computer to ports on docker container
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:5678:5678"

  webserver:
    build:
      context: ./equifax/webserver
    container_name: webserver_container
    restart: always
    networks:
      db_network:
        ipv4_address: 192.168.201.20
      web_network:
        ipv4_address: 192.168.200.20
    ports:
      - "127.0.0.1:8080:8080"

  db:
    build:
      context: ./equifax/database
    container_name: db_container
    restart: always
    networks:
      db_network:
        ipv4_address: 192.168.201.100

  # new admin environment
  adminserver: 
    build: 
      context: ./adminserver
    container_name: adminserver_container
    restart: always
    networks:
      # connect to the web network 
      web_network:
        ipv4_address: 192.168.200.30 

volumes:
  venv-volume:
  frontend-ignore:
