-- Production billing database backup
-- Generated by nightly-backup-job
-- Environment: production

CREATE TABLE customers (
  customer_id INTEGER PRIMARY KEY,
  name TEXT,
  email TEXT,
  status TEXT
);

CREATE TABLE payments (
  payment_id INTEGER PRIMARY KEY,
  customer_id INTEGER,
  amount_cents INTEGER,
  payment_date TEXT
);

INSERT INTO customers VALUES (1001, 'Alice Carter', 'alice.carter@example.com', 'active');
INSERT INTO payments VALUES (5001, 1001, 2499, '2026-03-14');